### ISSUE TITLE
ERROR EXPLANATION

### ISSUE THREAD

**Issue by gloplus** [jwage/php-mongodb-admin#21]
This is what i see after running the code, 

  **| Mongo support required. Install mongo pecl extension with 'pecl install mongo; echo "extension=mongo.so" >> php.ini'**
-- | --
PLEASE I ALREADY HAVE MONGODB RUNNING ON MY LOCAL SYSTEM, BUT I USE WINDOWS. PLEASE IS THIS A PROBLEM?

**Comment by jwage** [comment]
This tool is no longer used or maintained.
